services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    command: >
      bash -c "export MYSQL_HOST=\"$$(dig +short mysql)\" &&
               pnpm start:dev
              "
  
  mysql:
    image: mysql:8.0
    restart: "always"
    ports:
      - 3306:3306
    volumes:
      - ./docker-volumes/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?err}
      - MYSQL_USER=${MYSQL_USER:?err}
      - MYSQL_DATABASE=${MYSQL_DATABASE:?err}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?err}
    healthcheck: 
      test: "mysql -u $${MYSQL_USER} -p$${MYSQL_PASSWORD} -h localhost -e 'SELECT 1'"
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  nginx:
    image: 'nginx:stable'
    depends_on:
      - api
    links:
      - api
    restart: always
    ports:
      - 3000:80
    volumes:
      - './deployment/nginx.conf:/etc/nginx/nginx.conf'
